class_name CombatAction
extends RefCounted

## The combat verbs, and their mapping onto Godot input actions.
##
## Gameplay code refers to these enum values, never to input-action strings.
## That indirection is what lets the same combat system be driven by a player, by
## AI, or by a scripted test sequence without any of them knowing about devices.
## An AI does not "press K" — it intends PUNCH.
##
## Never reorder these values: they are stored in the input buffer as ints and
## used as bit positions. Append only.

enum Id {
	PUNCH,           ## K / pad X
	KICK,            ## J / pad Y
	JUMP,            ## Space / pad A
	DASH,            ## Shift / pad RB
	GUARD,           ## Q / pad LB
	SOUL_TECHNIQUE,  ## E / pad B
	MANIFESTATION,   ## R / pad RT
	LOCK_ON,         ## Tab / right stick click
	INTERACT,        ## F / D-pad up
}

## Count of defined actions. Used to size bitmasks and validate ids.
const COUNT: int = 9

## Enum id -> the InputMap action name generated by tools/generate_input_map.gd.
## The single place device bindings meet gameplay intent.
const INPUT_NAMES: Dictionary = {
	Id.PUNCH:          &"punch",
	Id.KICK:           &"kick",
	Id.JUMP:           &"jump",
	Id.DASH:           &"dash",
	Id.GUARD:          &"guard",
	Id.SOUL_TECHNIQUE: &"soul_technique",
	Id.MANIFESTATION:  &"manifestation",
	Id.LOCK_ON:        &"lock_on",
	Id.INTERACT:       &"interact",
}

## Actions that initiate or feed an attack. Used when deciding whether a
## buffered input should be considered for a combo-graph edge.
const ATTACK_ACTIONS: Array[Id] = [Id.PUNCH, Id.KICK, Id.SOUL_TECHNIQUE]


static func bit(id: Id) -> int:
	return 1 << int(id)


static func input_name(id: Id) -> StringName:
	return INPUT_NAMES.get(id, &"")


static func display_name(id: Id) -> String:
	match id:
		Id.PUNCH:          return "Punch"
		Id.KICK:           return "Kick"
		Id.JUMP:           return "Jump"
		Id.DASH:           return "Dash"
		Id.GUARD:          return "Guard"
		Id.SOUL_TECHNIQUE: return "Soul Technique"
		Id.MANIFESTATION:  return "Manifestation"
		Id.LOCK_ON:        return "Lock On"
		Id.INTERACT:       return "Interact"
	return "Unknown"


static func is_attack(id: Id) -> bool:
	return id in ATTACK_ACTIONS


## All ids, for iteration without hardcoding the list at each call site.
static func all() -> Array[Id]:
	var result: Array[Id] = []
	for i: int in COUNT:
		result.append(i as Id)
	return result
